### ISSUE TITLE
[Fatal, Error:FreddyKrueger]

### ISSUE THREAD

**Issue by CoolLKKPS** [FelixAllard/FreddyKrueger-LC#3]
[Error  : Unity Log] KeyNotFoundException: The given key '43' was not present in the dictionary.
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <787acc3c9a4c471ba7d971300105af24>:IL_001E)
LethalNetworkAPI.LethalNetworkExtensions.GetPlayerController (System.UInt64 clientId) (at ./LethalNetworkExtensions.cs:18)
FreddyKruegerLC.SleepMechanics.CheckIfAlone (GameNetcodeStuff.PlayerControllerB player) (at ./src/FreddyKrueger/SleepMechanics.cs:169)
FreddyKruegerLC.SleepMechanics.UpdateSleep () (at ./src/FreddyKrueger/SleepMechanics.cs:75)
FreddyKruegerLC.FreddyAi.Update () (at ./src/FreddyKrueger/FreddyAi.cs:217)

[Fatal, Error:FreddyKrueger] Removing Player From array

[Error  : Unity Log] KeyNotFoundException: The given key '43' was not present in the dictionary.
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <787acc3c9a4c471ba7d971300105af24>:IL_001E)
LethalNetworkAPI.LethalNetworkExtensions.GetPlayerController (System.UInt64 clientId) (at ./LethalNetworkExtensions.cs:18)
FreddyKruegerLC.SleepMechanics.UpdateSleep () (at ./src/FreddyKrueger/SleepMechanics.cs:73)
FreddyKruegerLC.FreddyAi.Update () (at ./src/FreddyKrueger/FreddyAi.cs:217)

this is my first time get Fatal Error in the game

**Comment by CoolLKKPS** [comment]
also can u make the audio not spamming in my ear?

**Comment by CoolLKKPS** [comment]
uh deprecated?! @FelixAllard

**Comment by FelixAllard** [comment]
Sorry, been quite busy with stuff
Yeah, so Right now, I am in the process of remaking the whole AI because it broken with the new version. I deprecated it just so people understand I can't suggest playing with it at the moment. The voicelines spamming will also be solved  XD.
It is only temporary and it will be fixed soon!

**Comment by CoolLKKPS** [comment]
oh ok, and btw can difficulty go too far if with [OopsAllFlooded](https://thunderstore.io/c/lethal-company/p/squirrelboydev/OopsAllFlooded) mod? @FelixAllard

**Comment by FelixAllard** [comment]
I am not sure I understand the question, @CoolLKKPS , but if it is what I think, yes the difficulty can be really hard as Freddy could force you to go underwater. Usually, this would only happen if you stay for a long time because Freddy doesn't spawn unless his sleep mechanic activate (260 seconds alone)

**Comment by CoolLKKPS** [comment]
i prepare a mechanism which can make player can stay under the water, the mod name call oxygen, and allflood mod can make indoor fill with water and that can slow player speed
so if freddy can have normal speed to chase player under the water, for me the balance will break

**Comment by CoolLKKPS** [comment]
OK I figured out how to balance, so just fix those issue and i think it should compatible with that mod and difficulty won't go too far

**Comment by FelixAllard** [comment]
Hello there! 
Sorry, been real busy. So basically Freddy uses the same movement system as all the other monsther meaning he uses a NavMeshAgent to move around. That means he won't be slowed down by water in any way. You could modify Freddy's agent.speed variable by finding freddy in the scene, that would work. Else, if you need a variable which you can use to slow down freddy i instaured one already it is just not public yet! Need to redo the whole ai, but it shouldn't change much
Once again sorry for the late reply, school is just really huge right now!

**Comment by CoolLKKPS** [comment]
ok, no rush >:)

**Comment by CoolLKKPS** [comment]
@FelixAllard uh really like this cool mod, so uh can u update this mod in a few days?

**Comment by CoolLKKPS** [comment]
and NightmareFoxy

**Comment by FelixAllard** [comment]
Yeah, sorry, I was in my end of semester, and I didn't find the time to work on it,  but now I am back! I'll be fixing Foxy for it is a small fix supposidly, and then I'll fix Freddy. This should be done within this week

**Comment by CoolLKKPS** [comment]
woohoo!!!

**Comment by CoolLKKPS** [comment]
sorry i can't wait so much time...
